// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATIvI_Jn0qg5wonp2-chA5SqhxYXekTvg',
    appId: '1:329191067811:web:8332e7005cc71ee09e6f16',
    messagingSenderId: '329191067811',
    projectId: 'allfood-85150',
    authDomain: 'allfood-85150.firebaseapp.com',
    storageBucket: 'allfood-85150.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjTPtl40L9e0_cW5g0Wzx9dXX7EsCGgZc',
    appId: '1:329191067811:android:a1f454b0e3a57da69e6f16',
    messagingSenderId: '329191067811',
    projectId: 'allfood-85150',
    storageBucket: 'allfood-85150.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4_Hfuo99dNfqkB674g9_5alZtDs592cQ',
    appId: '1:329191067811:ios:e7b7fed2a380cbac9e6f16',
    messagingSenderId: '329191067811',
    projectId: 'allfood-85150',
    storageBucket: 'allfood-85150.firebasestorage.app',
    iosBundleId: 'com.allfood.allFood',
  );
}
